/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 developer.glb -T 
Files: developer.glb [981.62KB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/developer-transformed.glb [395.08KB] (60%)
*/

import React, { useEffect, useRef, useMemo } from 'react';
import { useGraph } from '@react-three/fiber';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

// Preload all animations at module level to avoid loading during render
const idleAnimationPromise = import('@react-three/drei').then(() => 
  useFBX.preload('/models/animations/idle.fbx')
);
const saluteAnimationPromise = import('@react-three/drei').then(() => 
  useFBX.preload('/models/animations/salute.fbx')
);
const clappingAnimationPromise = import('@react-three/drei').then(() => 
  useFBX.preload('/models/animations/clapping.fbx')
);
const victoryAnimationPromise = import('@react-three/drei').then(() => 
  useFBX.preload('/models/animations/victory.fbx')
);

const Developer = ({ animationName = 'idle', ...props }) => {
  const group = useRef();

  const { scene } = useGLTF('/models/animations/developer.glb');
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  // Load animations with proper error handling
  const idleAnimation = useFBX('/models/animations/idle.fbx');
  const saluteAnimation = useFBX('/models/animations/salute.fbx');
  const clappingAnimation = useFBX('/models/animations/clapping.fbx');
  const victoryAnimation = useFBX('/models/animations/victory.fbx');

  // Process animations in useMemo to avoid re-processing on every render
  const processedAnimations = useMemo(() => {
    const animations = [];
    
    if (idleAnimation?.animations?.[0]) {
      const idle = idleAnimation.animations[0].clone();
      idle.name = 'idle';
      animations.push(idle);
    }
    
    if (saluteAnimation?.animations?.[0]) {
      const salute = saluteAnimation.animations[0].clone();
      salute.name = 'salute';
      animations.push(salute);
    }
    
    if (clappingAnimation?.animations?.[0]) {
      const clapping = clappingAnimation.animations[0].clone();
      clapping.name = 'clapping';
      animations.push(clapping);
    }
    
    if (victoryAnimation?.animations?.[0]) {
      const victory = victoryAnimation.animations[0].clone();
      victory.name = 'victory';
      animations.push(victory);
    }
    
    return animations;
  }, [idleAnimation, saluteAnimation, clappingAnimation, victoryAnimation]);

  const { actions } = useAnimations(processedAnimations, group);

  useEffect(() => {
    // Only play animation if it exists and is loaded
    if (actions[animationName]) {
      // Stop all other animations first
      Object.values(actions).forEach(action => {
        if (action !== actions[animationName]) {
          action.stop();
        }
      });
      
      actions[animationName].reset().fadeIn(0.5).play();
      
      return () => {
        if (actions[animationName]) {
          actions[animationName].fadeOut(0.5);
        }
      };
    }
  }, [animationName, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair?.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair?.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses?.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses?.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body?.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body?.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom?.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom?.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear?.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear?.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top?.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top?.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft?.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft?.skeleton}
        morphTargetDictionary={nodes.EyeLeft?.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft?.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight?.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight?.skeleton}
        morphTargetDictionary={nodes.EyeRight?.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight?.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head?.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head?.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head?.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head?.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth?.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth?.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth?.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth?.morphTargetInfluences}
      />
    </group>
  );
};

// Preload all resources
useGLTF.preload('/models/animations/developer.glb');
useFBX.preload('/models/animations/idle.fbx');
useFBX.preload('/models/animations/salute.fbx');
useFBX.preload('/models/animations/clapping.fbx');
useFBX.preload('/models/animations/victory.fbx');

export default Developer;