/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Meee (https://sketchfab.com/Meee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-hologram-87072288fb234226b9a3f02ae674a310
Title: Earth hologram
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function EarthHologram(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/earth_hologram.glb')
  const { actions } = useAnimations(animations, group)
  
  // Auto-rotate the earth
  useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * 0.2 // Slow rotation
    }
  })

  // Start animations when component mounts
  useEffect(() => {
    // Start all available animations
    Object.values(actions).forEach((action) => {
      if (action) {
        action.play()
      }
    })
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.306}>
          <group name="Root">
            {/* Main Earth */}
            <group name="TERRE1" scale={3.27}>
              <mesh
                name="TERRE1_0"
                castShadow
                receiveShadow
                geometry={nodes.TERRE1_0.geometry}
                material={materials['Material.005']}
              />
            </group>
            
            {/* Atmosphere/Glow effect */}
            <group name="Sphere002" rotation={[0, 0, -3.015]} scale={0.965}>
              <mesh
                name="Sphere002_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_0.geometry}
                material={materials['Material.006']}
              />
            </group>
            
            {/* Hologram ring effects */}
            <group name="Circle643" scale={4.787}>
              <mesh
                name="Circle643_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle643_0.geometry}
                material={materials['Material.004']}
              />
            </group>
            
            {/* Small hologram elements */}
            <group name="Circle455" scale={0.176}>
              <mesh
                name="Circle455_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle455_0.geometry}
                material={materials['Material.007']}
                morphTargetDictionary={nodes.Circle455_0.morphTargetDictionary}
                morphTargetInfluences={nodes.Circle455_0.morphTargetInfluences}
              />
            </group>
            
            {/* Orbital rings with orbiting object */}
            <group name="Circle" scale={6.128}>
              <mesh
                name="Circle_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle_0.geometry}
                material={materials['Material.010']}
              />
              <group name="Icosphere002" position={[1, 0, 0]} scale={0.063}>
                <mesh
                  name="Icosphere002_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Icosphere002_0.geometry}
                  material={materials['Material.008']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

// Preload the model
useGLTF.preload('models/earth_hologram.glb')