// import { useGLTF } from '@react-three/drei';
// import { useRef } from 'react';
// import { useGSAP } from '@gsap/react';
// import gsap from 'gsap';

// const Target = (props) => {
//   const targetRef = useRef();
//   const { scene } = useGLTF(
//     'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target-stand/model.gltf',
//   );

//   useGSAP(() => {
//     gsap.to(targetRef.current.position, {
//       y: targetRef.current.position.y + 0.5,
//       duration: 1.5,
//       repeat: -1,
//       yoyo: true,
//     });
//   });

//   return (
//     <mesh {...props} ref={targetRef} rotation={[0, Math.PI / 5, 0]} scale={1.5}>
//       <primitive object={scene} />
//     </mesh>
//   );
// };

// export default Target;


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Denys Almaral (https://sketchfab.com/denysalmaral)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-humanoid-robot-bad584b9fbe04c85bc57438842969270
Title: Low Poly Humanoid Robot
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from "three"

const ProfessionalWalkingCharacter = (props) => {
  const group = useRef();
  const walkDirection = useRef(1);
  const walkSpeed = 0.03;
  const walkBounds = { left: -15, right: 15 };
  
  const { nodes, materials, animations } = useGLTF('models/low_poly_humanoid_robot.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play walking animation if available
    if (actions && Object.keys(actions).length > 0) {
      // Try to find walking animation
      const walkAnimation = Object.keys(actions).find(name => 
        name.toLowerCase().includes('walk') || 
        name.toLowerCase().includes('run') ||
        name.toLowerCase().includes('move')
      );
      
      // If no walk animation found, play the first available animation
      const animationToPlay = walkAnimation || Object.keys(actions)[0];
      
      if (actions[animationToPlay]) {
        // Set the animation to loop continuously
        actions[animationToPlay].reset().fadeIn(0.5);
        actions[animationToPlay].setLoop(THREE.LoopRepeat, Infinity); // Use THREE.LoopRepeat
        actions[animationToPlay].play();
        console.log(`Playing animation: ${animationToPlay}`);
      }
    
    }
    
    // Log available animations for debugging
    console.log('Available animations:', Object.keys(actions || {}));
  }, [actions]);

  // Walking movement
  useFrame(() => {
    if (group.current) {
      // Move the robot
      group.current.position.x += walkDirection.current * walkSpeed;
      
      // Check bounds and change direction
      if (group.current.position.x >= walkBounds.right) {
        walkDirection.current = -1;
        group.current.rotation.y = Math.PI; // Face left
      } else if (group.current.position.x <= walkBounds.left) {
        walkDirection.current = 1;
        group.current.rotation.y = 0; // Face right
      }
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group 
            name="LowPolyRobotfbx" 
            rotation={[ 2, 2, 0]} 
            scale={.05} // Increased scale to make it visible
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.lpRobot}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="robot_lp" rotation={[-Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('models/low_poly_humanoid_robot.glb');

export default ProfessionalWalkingCharacter;